/**
 * AZM code generator.
 *
 * Turns a GlimmerProgram into a single generated AZM source file:
 * API equates, change-flag constants, state storage, the runtime loop,
 * binding polling, phase dispatch, wrapped user blocks and frame cleanup.
 *
 * The output follows the shape described in docs/glimmer.md section 10.3 and
 * uses canonical AZM style (lowercase dotted directives).
 */

import type { EffectDecl, GlimmerDiagnostic, GlimmerProgram } from './model.js';
import { EFFECT_PHASES, TEC1G_KEY_CODES } from './model.js';

export interface GenerateOptions {
  /** Assembly origin for the generated program. Default: $4000. */
  org?: number;
  /** Base address for the placeholder system API jump table. Default: $8000. */
  apiBase?: number;
}

export interface GenerateResult {
  source: string;
  diagnostics: GlimmerDiagnostic[];
}

const DEFAULT_ORG = 0x4000;
const DEFAULT_API_BASE = 0x8000;

/** Placeholder system API entries until a real platform profile exists. */
const API_NAMES = ['API_ReadKeys', 'API_DrawChar', 'API_FlushDisplay', 'API_InitDisplay'];

function hex(value: number, digits: number): string {
  return `$${value.toString(16).toUpperCase().padStart(digits, '0')}`;
}

function bin8(value: number): string {
  return `%${value.toString(2).padStart(8, '0')}`;
}

function chgConst(cellName: string): string {
  return `CHG_${cellName.toUpperCase()}`;
}

/**
 * Namespace block-local labels ("_done") into ordinary globally unique
 * AZM labels ("Glim_ApplyIncrement_done"). Only labels defined inside the
 * block are rewritten.
 *
 * "$" is not user-facing label syntax in AZM (it is the current-address
 * operator and hex-literal prefix), so generated labels use a plain
 * underscore separator. Label privacy is AZM's .import/@ mechanism, not a
 * naming convention.
 */
export function namespaceLocalLabels(body: string[], effectName: string): string[] {
  const localNames = new Set<string>();
  for (const line of body) {
    const def = /^\s*_([A-Za-z][A-Za-z0-9_]*):/.exec(line);
    if (def) localNames.add(def[1] as string);
  }
  if (localNames.size === 0) return body;
  return body.map((line) =>
    line.replace(
      /(^|[^A-Za-z0-9_])_([A-Za-z][A-Za-z0-9_]*)/g,
      (whole, prefix: string, name: string) =>
        localNames.has(name) ? `${prefix}Glim_${effectName}_${name}` : whole,
    ),
  );
}

export function generateAzm(
  program: GlimmerProgram,
  options: GenerateOptions = {},
): GenerateResult {
  const diagnostics: GlimmerDiagnostic[] = [];
  const org = options.org ?? DEFAULT_ORG;
  const apiBase = options.apiBase ?? DEFAULT_API_BASE;

  // v0 uses a single change-flag byte: states first, then pulses.
  const trackedCells = [...program.states.map((s) => s.name), ...program.pulses.map((p) => p.name)];
  if (trackedCells.length > 8) {
    diagnostics.push({
      line: 0,
      message: `Changed0 is full: ${trackedCells.length} state/pulse cells declared, v0 supports at most 8.`,
    });
    return { source: '', diagnostics };
  }
  const chgBit = new Map(trackedCells.map((name, index) => [name, index]));

  const isTec1g = program.platform === 'tec1g-mon3';

  // Generic profile: key bits are assigned in order of first appearance.
  // tec1g-mon3 uses MON-3 key codes instead; no bit budget applies.
  const keyBit = new Map<string, number>();
  if (!isTec1g) {
    for (const binding of program.bindings) {
      if (!keyBit.has(binding.key)) keyBit.set(binding.key, keyBit.size);
    }
    if (keyBit.size > 8) {
      diagnostics.push({
        line: 0,
        message: `Too many distinct keys: ${keyBit.size}, v0 supports at most 8 (one input byte).`,
      });
      return { source: '', diagnostics };
    }
  }

  const out: string[] = [];
  const emit = (line = ''): void => {
    out.push(line);
  };
  const op = (text: string): void => {
    emit(`        ${text}`);
  };

  emit(`; Generated by Glimmer from program ${program.name}.`);
  emit('; Do not edit: regenerate from the Glimmer source.');
  emit();
  op(`.org    ${hex(org, 4)}`);
  emit();

  if (isTec1g) {
    emit('; --- TEC-1G / MON-3 platform ---');
    emit(`${'ApiScanKeys'.padEnd(17)} .equ 16`);
    emit(`${'PortRow'.padEnd(17)} .equ $05`);
    emit(`${'PortRed'.padEnd(17)} .equ $06`);
    emit(`${'PortGreen'.padEnd(17)} .equ $F8`);
    emit(`${'PortBlue'.padEnd(17)} .equ $F9`);
    emit(`${'ScanDwellPeriod'.padEnd(17)} .equ 255`);
    emit(`${'COLOR_RED'.padEnd(17)} .equ $01`);
    emit(`${'COLOR_GREEN'.padEnd(17)} .equ $02`);
    emit(`${'COLOR_BLUE'.padEnd(17)} .equ $04`);
    emit(`${'COLOR_WHITE'.padEnd(17)} .equ $07`);
    emit();
    const usedKeys = [...new Set(program.bindings.map((b) => b.key))];
    if (usedKeys.length > 0) {
      emit('; --- MON-3 key codes ---');
      for (const key of usedKeys) {
        emit(`${key.padEnd(17)} .equ ${hex(TEC1G_KEY_CODES.get(key) ?? 0, 2)}`);
      }
      emit();
    }
  } else {
    emit('; --- system API (placeholder addresses) ---');
    API_NAMES.forEach((name, index) => {
      emit(`${name.padEnd(17)} .equ ${hex(apiBase + index * 3, 4)}`);
    });
    emit();

    if (keyBit.size > 0) {
      emit('; --- key bits ---');
      for (const [key, bit] of keyBit) {
        emit(`${`${key}_BIT`.padEnd(17)} .equ ${bit}`);
      }
      emit();
    }
  }

  emit('; --- change flags ---');
  for (const [name, bit] of chgBit) {
    emit(`${`${chgConst(name)}_BIT`.padEnd(17)} .equ ${bit}`);
  }
  for (const [name, bit] of chgBit) {
    emit(`${chgConst(name).padEnd(17)} .equ ${bin8(1 << bit)}`);
  }
  emit();

  const effectsByPhase = new Map(
    EFFECT_PHASES.map((phase) => [phase, program.effects.filter((e) => e.phase === phase)]),
  );

  emit('; --- effect dependency masks ---');
  for (const effect of program.effects) {
    const mask = effect.depends.map(chgConst).join(' + ');
    emit(`${`GlimDep_${effect.name}`.padEnd(17)} .equ ${mask}`);
  }
  emit();

  emit('; --- state storage ---');
  for (const state of program.states) {
    const directive = state.type === 'word' ? '.dw' : '.db';
    emit(`${`${state.name}:`.padEnd(17)} ${directive} ${state.initial}`);
  }
  for (const pulse of program.pulses) {
    emit(`${`${pulse.name}:`.padEnd(17)} .db 0`);
  }
  if (!isTec1g) {
    emit(`${'PrevKeys:'.padEnd(17)} .db 0`);
  }
  const initialChanged = program.states
    .filter((state) => state.changedOnStart)
    .map((state) => 1 << (chgBit.get(state.name) as number))
    .reduce((acc, mask) => acc | mask, 0);
  emit(`${'Changed0:'.padEnd(17)} .db ${bin8(initialChanged)}`);
  if (isTec1g) {
    emit(`${'Framebuffer:'.padEnd(17)} .ds 32           ; 8 rows x R,G,B,aux`);
  }
  emit();

  emit('; --- runtime loop ---');
  emit('@Start:');
  if (isTec1g) {
    op('call    FbClear');
    emit('MainLoop:');
    op('call    ScanFrame            ; show one full frame, then blank');
    op('call    __PollBindings       ; game work runs in the blank window');
  } else {
    op('call    API_InitDisplay');
    emit('MainLoop:');
    op('call    __PollBindings');
  }
  for (const phase of EFFECT_PHASES) {
    if ((effectsByPhase.get(phase) ?? []).length > 0) {
      op(`call    __Run${capitalize(phase)}Effects`);
    }
  }
  if (!isTec1g) {
    op('call    API_FlushDisplay');
  }
  op('call    __ClearFrameState');
  op('jp      MainLoop');
  emit();

  if (isTec1g) {
    emitTec1gPollBindings(program, emit, op);
  } else {
    emitPollBindings(program, emit, op);
  }

  for (const phase of EFFECT_PHASES) {
    const effects = effectsByPhase.get(phase) ?? [];
    if (effects.length === 0) continue;
    emit(`; --- ${phase} phase dispatch ---`);
    emit(';! clobbers A,BC,DE,HL,IX,IY');
    emit(`@__Run${capitalize(phase)}Effects:`);
    for (const effect of effects) {
      op('ld      a,(Changed0)');
      op(`and     GlimDep_${effect.name}`);
      op(`jr      z,GlimSkip_${effect.name}`);
      op(`call    Glim_${effect.name}`);
      emit(`GlimSkip_${effect.name}:`);
    }
    op('ret');
    emit();
  }

  for (const effect of program.effects) {
    emitEffectWrapper(effect, emit, op);
  }

  emit('; --- frame cleanup ---');
  emit(';! clobbers A');
  emit('@__ClearFrameState:');
  op('xor     a');
  for (const pulse of program.pulses) {
    op(`ld      (${pulse.name}),a`);
  }
  op('ld      (Changed0),a');
  op('ret');

  if (isTec1g) {
    emit();
    emitMatrixLibrary(emit, op);
  }

  return { source: `${out.join('\n')}\n`, diagnostics };
}

/**
 * tec1g-mon3 input polling. MON-3 _scanKeys (RST $10, C=16) returns the
 * key code in A with Z set while a key is pressed and carry set only on
 * a new press, so rising-edge pulses need no PrevKeys shadow.
 */
function emitTec1gPollBindings(
  program: GlimmerProgram,
  emit: (line?: string) => void,
  op: (text: string) => void,
): void {
  emit('; --- input polling (MON-3 _scanKeys) ---');
  emit(';! clobbers A,BC,DE');
  emit('@__PollBindings:');
  if (program.bindings.length === 0) {
    op('ret');
    emit();
    return;
  }
  op('ld      c,ApiScanKeys');
  op('rst     $10');
  op('ret     nz                   ; no key pressed');
  op('ret     nc                   ; key held, not a new press');
  op('ld      b,a                  ; B = key code (DE unsafe: matrix kbd)');
  for (const binding of program.bindings) {
    op('ld      a,b');
    op(`cp      ${binding.key}`);
    op(`jr      nz,__NoPulse_${binding.target}_${binding.key}`);
    op('ld      a,1');
    op(`ld      (${binding.target}),a`);
    op('ld      a,(Changed0)');
    op(`or      ${chgConst(binding.target)}`);
    op('ld      (Changed0),a');
    op('ret');
    emit(`__NoPulse_${binding.target}_${binding.key}:`);
  }
  op('ret');
  emit();
}

/**
 * Matrix profile library: whole-frame scanout with fixed row dwell
 * (brightness stays uniform regardless of game-work cost) plus minimal
 * framebuffer helpers. Modeled on the corpus Tetro/Pacmo shared layer.
 */
function emitMatrixLibrary(emit: (line?: string) => void, op: (text: string) => void): void {
  emit('; --- matrix8x8 profile library ---');
  emit();
  emit('; Scan all 8 rows with fixed dwell, then blank the matrix so');
  emit('; effect work never changes visible row brightness.');
  emit(';! clobbers  A,BC,HL');
  emit('@ScanFrame:');
  op('ld      hl,Framebuffer');
  op('ld      c,%00000001          ; row select mask');
  emit('ScanFrameRow:');
  op('xor     a');
  op('out     (PortRow),a          ; blank before changing colour data');
  op('ld      a,(hl) \\ out (PortRed),a \\ inc hl');
  op('ld      a,(hl) \\ out (PortGreen),a \\ inc hl');
  op('ld      a,(hl) \\ out (PortBlue),a \\ inc hl');
  op('inc     hl                   ; skip aux byte');
  op('ld      a,c');
  op('out     (PortRow),a          ; enable row');
  op('ld      b,ScanDwellPeriod');
  emit('ScanFrameDwell:');
  op('djnz    ScanFrameDwell');
  op('rlc     c');
  op('jr      nc,ScanFrameRow      ; carry after 8th rotate');
  op('xor     a');
  op('out     (PortRow),a          ; matrix blank on return');
  op('ret');
  emit();
  emit('; Convert x (0-7, 0 = leftmost) to the matrix bit convention.');
  emit(';! in A; out A; clobbers B');
  emit('@MxMask:');
  op('or      a');
  op('ld      b,a');
  op('ld      a,%10000000');
  op('ret     z');
  emit('MxMaskLp:');
  op('srl     a');
  op('djnz    MxMaskLp');
  op('ret');
  emit();
  emit('; Set one pixel. B = x (0-7), C = y (0-7), A = colour bits');
  emit('; (COLOR_RED/GREEN/BLUE, OR-combined). ORs into the framebuffer.');
  emit(';! in A,B,C; clobbers A,B,DE,HL');
  emit('@FbPlot:');
  op('ld      d,a                  ; D = colour bits');
  op('ld      a,c');
  op('add     a,a \\ add a,a       ; y * 4');
  op('ld      e,a');
  op('ld      a,b');
  op('call    MxMask               ; A = pixel mask');
  op('ld      b,a');
  op('ld      hl,Framebuffer');
  op('ld      a,l \\ add a,e \\ ld l,a');
  op('ld      a,h \\ adc a,0 \\ ld h,a');
  op('srl     d');
  op('jr      nc,FbPlotGrn');
  op('ld      a,(hl) \\ or b \\ ld (hl),a');
  emit('FbPlotGrn:');
  op('inc     hl');
  op('srl     d');
  op('jr      nc,FbPlotBlu');
  op('ld      a,(hl) \\ or b \\ ld (hl),a');
  emit('FbPlotBlu:');
  op('inc     hl');
  op('srl     d');
  op('ret     nc');
  op('ld      a,(hl) \\ or b \\ ld (hl),a');
  op('ret');
  emit();
  emit('; Clear the whole framebuffer.');
  emit(';! clobbers  A,B,HL');
  emit('@FbClear:');
  op('ld      hl,Framebuffer');
  op('ld      b,32');
  op('xor     a');
  emit('FbClearLp:');
  op('ld      (hl),a \\ inc hl');
  op('djnz    FbClearLp');
  op('ret');
}

function capitalize(text: string): string {
  return text.charAt(0).toUpperCase() + text.slice(1);
}

function emitPollBindings(
  program: GlimmerProgram,
  emit: (line?: string) => void,
  op: (text: string) => void,
): void {
  emit('; --- input polling ---');
  emit(';! clobbers A,BC,DE');
  emit('@__PollBindings:');
  if (program.bindings.length === 0) {
    op('ret');
    emit();
    return;
  }
  op('call    API_ReadKeys');
  op('ld      b,a');
  emit();
  op('ld      a,(PrevKeys)          ; rising edge = now AND NOT before');
  op('cpl');
  op('and     b');
  op('ld      c,a');
  emit();
  op('ld      a,b');
  op('ld      (PrevKeys),a');
  emit();
  for (const binding of program.bindings) {
    op(`bit     ${binding.key}_BIT,c`);
    op(`jr      z,__NoPulse_${binding.target}`);
    op('ld      a,1');
    op(`ld      (${binding.target}),a`);
    op('ld      a,(Changed0)');
    op(`or      ${chgConst(binding.target)}`);
    op('ld      (Changed0),a');
    emit(`__NoPulse_${binding.target}:`);
  }
  op('ret');
  emit();
}

function emitEffectWrapper(
  effect: EffectDecl,
  emit: (line?: string) => void,
  op: (text: string) => void,
): void {
  emit(`; --- effect ${effect.name} (${effect.phase}) ---`);
  emit(';! clobbers A,BC,DE,HL,IX,IY');
  emit(`@Glim_${effect.name}:`);
  for (const line of namespaceLocalLabels(effect.body, effect.name)) {
    emit(line);
  }
  for (const target of effect.updates) {
    op('ld      a,(Changed0)');
    op(`or      ${chgConst(target)}`);
    op('ld      (Changed0),a');
  }
  op('ret');
  emit();
}
